test-backend:
  stage: test
  image: oven/bun:1
  script:
    - cd backend
    - bun install
    - bun test
  coverage: '/(\d+) pass/'

test-frontend:
  stage: test
  image: node:24
  script:
    - cd frontend
    - npm install
    - npm run lint
    - npm test
  coverage: '/(\d+) passed/'
