workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    
    - if: $CI_COMMIT_BRANCH == "develop"
      when: always

    - if: $CI_PIPELINE_SOURCE == "merge_request_event" 
      when: always

    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      when: always

    - if: $CI_PIPELINE_SOURCE == "web"
      when: always

test-backend:
  stage: test
  image: oven/bun:1
  script:
    - cd backend
    - bun install
    - bun test
  coverage: '/(\d+) pass/'

test-frontend:
  stage: test
  image: node:24
  script:
    - cd frontend
    - npm install
    - npm run lint
    - npm test
  coverage: '/(\d+) passed/'
